language: php

sudo: false

cache:
  directory:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - composer --prefer-source install
  - mv vendor/wimg/php-compatibility vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PHPCompatibility

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PHPCompatibility ./lib/ ./tests/
